// <auto-generated />
using System;
using Autorizacion.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Autorizacion.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    partial class AuthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Autorizacion.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Autorizacion.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CiudadId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CiudadId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AyudasSociales.Models.AyudaComuna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AyudaSocialId")
                        .HasColumnType("int");

                    b.Property<int>("CiudadId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AyudaSocialId");

                    b.HasIndex("CiudadId");

                    b.ToTable("AyudaComuna");
                });

            modelBuilder.Entity("AyudasSociales.Models.AyudaRegion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AyudaSocialId")
                        .HasColumnType("int");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AyudaSocialId");

                    b.HasIndex("RegionId");

                    b.ToTable("AyudaRegion");
                });

            modelBuilder.Entity("AyudasSociales.Models.AyudaSocial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Anio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("AyudasSociales");
                });

            modelBuilder.Entity("AyudasSociales.Models.AyudaUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AyudaSocialId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AyudaSocialId");

                    b.HasIndex("UserId");

                    b.ToTable("AyudasUsuarios");
                });

            modelBuilder.Entity("AyudasSociales.Models.Ciudad", b =>
                {
                    b.Property<int>("CiudadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CiudadId"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("CiudadId");

                    b.HasIndex("RegionId");

                    b.ToTable("Ciudad");
                });

            modelBuilder.Entity("AyudasSociales.Models.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Siglas")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pais");
                });

            modelBuilder.Entity("AyudasSociales.Models.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegionId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.Property<string>("Siglas")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegionId");

                    b.HasIndex("PaisId");

                    b.ToTable("Region");
                });

            modelBuilder.Entity("Autorizacion.Models.User", b =>
                {
                    b.HasOne("AyudasSociales.Models.Ciudad", "Ciudad")
                        .WithMany("Usuarios")
                        .HasForeignKey("CiudadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Autorizacion.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ciudad");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AyudasSociales.Models.AyudaComuna", b =>
                {
                    b.HasOne("AyudasSociales.Models.AyudaSocial", "Ayuda")
                        .WithMany("AyudaComunas")
                        .HasForeignKey("AyudaSocialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AyudasSociales.Models.Ciudad", "Ciudad")
                        .WithMany("AyudaComunas")
                        .HasForeignKey("CiudadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ayuda");

                    b.Navigation("Ciudad");
                });

            modelBuilder.Entity("AyudasSociales.Models.AyudaRegion", b =>
                {
                    b.HasOne("AyudasSociales.Models.AyudaSocial", "Ayuda")
                        .WithMany("AyudaRegiones")
                        .HasForeignKey("AyudaSocialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AyudasSociales.Models.Region", "Region")
                        .WithMany("AyudaRegiones")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ayuda");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("AyudasSociales.Models.AyudaUsuario", b =>
                {
                    b.HasOne("AyudasSociales.Models.AyudaSocial", "Ayuda")
                        .WithMany("AyudaUsuario")
                        .HasForeignKey("AyudaSocialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Autorizacion.Models.User", "User")
                        .WithMany("AyudaUsuario")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ayuda");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AyudasSociales.Models.Ciudad", b =>
                {
                    b.HasOne("AyudasSociales.Models.Region", "Region")
                        .WithMany("Ciudades")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("AyudasSociales.Models.Region", b =>
                {
                    b.HasOne("AyudasSociales.Models.Pais", "Pais")
                        .WithMany("Regiones")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Autorizacion.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Autorizacion.Models.User", b =>
                {
                    b.Navigation("AyudaUsuario");
                });

            modelBuilder.Entity("AyudasSociales.Models.AyudaSocial", b =>
                {
                    b.Navigation("AyudaComunas");

                    b.Navigation("AyudaRegiones");

                    b.Navigation("AyudaUsuario");
                });

            modelBuilder.Entity("AyudasSociales.Models.Ciudad", b =>
                {
                    b.Navigation("AyudaComunas");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("AyudasSociales.Models.Pais", b =>
                {
                    b.Navigation("Regiones");
                });

            modelBuilder.Entity("AyudasSociales.Models.Region", b =>
                {
                    b.Navigation("AyudaRegiones");

                    b.Navigation("Ciudades");
                });
#pragma warning restore 612, 618
        }
    }
}
